// Builds the local release and stamps it with the commit it came from.
//
// The repo pins version 0.0.0 in tauri.conf.json / Cargo.toml on purpose - the real number is
// injected by the release CI from the tag - so a locally built exe carries no version at all and
// nothing tells you which commit produced the binary behind your desktop shortcut. This writes that
// provenance to build-info.json beside the exe. The file lands in src-tauri/target/, which is
// already gitignored, so it cannot reach a commit or a release.

import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';

const ROOT = path.resolve(import.meta.dirname, '..');
const RELEASE_DIR = path.join(ROOT, 'src-tauri', 'target', 'release');
const STAMP = path.join(RELEASE_DIR, 'build-info.json');

const stampOnly = process.argv.includes('--stamp-only');
const closeApp = process.argv.includes('--close');

// The binary is named after the cargo package.
const cargoToml = fs.readFileSync(path.join(ROOT, 'src-tauri', 'Cargo.toml'), 'utf8');
const pkg = /^name = "(.+)"/m.exec(cargoToml)?.[1];
if (!pkg) throw new Error('no package name in src-tauri/Cargo.toml');
const exe = path.join(RELEASE_DIR, `${pkg}.exe`);

// A running app holds a lock on its own exe, so the link step fails - but only after minutes of
// compiling, with a linker error that says nothing about the real cause. Check before spending that
// time. Closing is opt-in rather than automatic: the app may be mid-conversation, and losing that to
// a build nobody asked to be destructive is worse than one extra command.
// notes: Windows-only detection (tasklist/taskkill). Other platforms skip the check and fall back to
//        whatever the linker reports, which is what happened here before this existed.
function appIsRunning() {
  if (process.platform !== 'win32') return false;
  const list = spawnSync('tasklist', ['/FI', `IMAGENAME eq ${pkg}.exe`, '/NH'], { encoding: 'utf8' });
  return (list.stdout ?? '').toLowerCase().includes(`${pkg}.exe`.toLowerCase());
}

async function closeRunningApp() {
  // No /F: plain taskkill asks the window to close, so the app still saves its settings on the way out.
  spawnSync('taskkill', ['/IM', `${pkg}.exe`], { stdio: 'inherit' });
  for (let waited = 0; waited < 10_000; waited += 250) {
    if (!appIsRunning()) return;
    await new Promise((resolve) => setTimeout(resolve, 250));
  }
  throw new Error(`${pkg}.exe is still running after asking it to close; close it by hand and retry`);
}

if (!stampOnly && appIsRunning()) {
  if (!closeApp) {
    throw new Error(`${pkg}.exe is running and holds its own exe locked. Close it, or run: pnpm build:local --close`);
  }
  await closeRunningApp();
}

if (!stampOnly) {
  // tauri.conf's beforeBuildCommand already runs "pnpm build:injected && pnpm build".
  // One command string, no args array: pnpm is a .cmd on Windows so it needs the shell, and passing
  // args alongside shell:true is deprecated (DEP0190).
  const build = spawnSync('pnpm tauri build', { cwd: ROOT, stdio: 'inherit', shell: true });
  if (build.status !== 0) throw new Error(`pnpm tauri build failed (${build.status})`);
}

if (!fs.existsSync(exe)) throw new Error(`no exe at ${exe}`);

const git = (...args) => spawnSync('git', ['-C', ROOT, ...args], { encoding: 'utf8' }).stdout.trim();

// Not `status --porcelain`: the tauri build itself rewrites src-tauri\Cargo.toml and the
// autogenerated permission TOMLs with CRLF, which would mark every single build dirty. Only real
// content counts.
const dirty = spawnSync('git', ['-C', ROOT, 'diff', '--quiet', '--ignore-cr-at-eol', 'HEAD']).status !== 0;

// Local time, no zone, seconds - the format version.ps1 reads, and it compares builtAt against the
// exe's own LastWriteTime to catch a stale stamp. UTC here would read as 8 hours stale.
const localIso = (date) => new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 19);

const info = {
  describe: git('describe', '--tags', '--always', 'HEAD'), // e.g. v1.8.4-2-g5f77ed5
  commit: git('rev-parse', 'HEAD'),
  branch: git('rev-parse', '--abbrev-ref', 'HEAD'),
  dirty, // true = the tree had uncommitted edits, describe understates it
  builtAt: localIso(fs.statSync(exe).mtime),
  stampedAt: localIso(new Date()),
};

fs.writeFileSync(STAMP, `${JSON.stringify(info, null, 2)}\n`);
process.stdout.write(`stamped ${info.describe} (branch ${info.branch}, dirty=${dirty}) -> ${STAMP}\n`);
